name: "Black Duck Scan"
description: "Black Duck Scanning NEW VERSION 2 for GitHub CI/CD Workflows"
author: "Matthew Brady"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  debug:
    description: "Debugging"
    default: "0"
    required: false
  url:
    description: "Black Duck URL"
    required: true
  token:
    description: "Black Duck API Token"
    required: true
  trustcert:
    description: "Trust Black Duck server certificate"
    required: false
  project:
    description: "Project name in the Black Duck server"
    required: false
  version:
    description: "Project version name in the Black Duck server"
    required: false
  mode:
    description: "Scanning mode, intelligent or rapid"
    default: "rapid"
    required: false
  file:
    description: "Location of the related file in the repository"
  output:
    description: "Directory in which to save the rapid scan output"
    default: "blackduck-output"
    required: false
  fix_pr:
    description: "Generate a Fix PR for each insecure component"
    default: "false"
    required: false
  comment_on_pr:
    description: "Comment on a pull request"
    default: "false"
  sarif:
    description: "Output file for SARIF"
    required: false
  incremental_results:
    description: "Incremental analysis"
    required: false
  upgrade_major:
    description: "Recommend upgrade guidance to major, not just minor, versions"
    required: false
  nocheck:
    description: "Skip check of GH commit/PR for changed package manager config files"
    required: false
  detect_opts:
    description: "Passthrough options to Detect, comma delimited, exclude leading hyphens"
    required: false
runs:
  using: "composite"
  steps:
    - run: python setup.py install  # Installing dependencies
      shell: bash
    - run: python ${{ github.action_path }}/bdscan/bdscanaction.py
      shell: bash
#   using: "docker"
# #  image: "Dockerfile"
#   image: "docker://ghcr.io/matthewb66/bdghscan2:latest"
  args:
    - --debug
    - ${{ inputs.debug }}
    - --url
    - ${{ inputs.url }}
    - --token
    - ${{ inputs.token }}
    - --trustcert
    - ${{ inputs.trustcert }}
    - --mode
    - ${{ inputs.mode }}
    - --output
    - ${{ inputs.output }}
    - --project
    - ${{ inputs.project }}
    - --version
    - ${{ inputs.version }}
    - --fix_pr
    - ${{ inputs.fix_pr }}
    - --comment_on_pr
    - ${{ inputs.comment_on_pr }}
    - --sarif
    - ${{ inputs.sarif }}
    - --incremental_results
    - ${{ inputs.incremental_results }}
    - --upgrade_major
    - ${{ inputs.upgrade_major }}
    - --nocheck
    - ${{ inputs.nocheck }}
    - --detect_opts
    - ${{ inputs.detect_opts }}
